### ISSUE TITLE
Define feature list & order by priority

### ISSUE THREAD

**Issue by okjuan** [Wubbadub/ClubHub#1]
Dynamic: https://paper.dropbox.com/doc/Clubhub-Feature-List-LbHFYliH17nfzlmCBbIoB
Static: https://github.com/Wubbadub/ClubHub/wiki/Feature-List

For each feature, give:
- name 
- current status
- est time until completion
- due date

_beware feature creep!_

**Comment by jcgallegdup** [comment]
Shared Doc WIP [https://docs.google.com/document/d/1cqwFa0A7Y1sEVoBAMxsGKx3U_G3uNnLevORlOOXdQJU/edit](url)

**Comment by kelseyll** [comment]
https://paper.dropbox.com/doc/Clubhub-Feature-List-LbHFYliH17nfzlmCBbIoB
