### ISSUE TITLE
Fix editor scrolling

### ISSUE THREAD

**Issue by bndnio** [Wubbadub/ClubHub#100]
__Description:__
Currently the editor guesses the bottom of the editor section using a hard-coded value, this breaks scrolling sometimes. Additionally scrolling when in the editor scrolls both the sidebar and the webpage - this isn't what a user would expect.

__Requires:__
* editor section to function

__Breakdown:__
- [x] Fix hard-coded padding
- [x] When the cursor is over the editor panel scroll only the editor, if the cursor is over the webpage scroll only the webpage

__Time Estimation:__
2 hrs.

**Comment by hwkr** [comment]
Note: it only scrolls both when the editor scroll tops out or bottoms out. They never both scroll at the same time. (We should still fix this) I think we just need to make the editor always capture scroll.

**Comment by bndnio** [comment]
Do you mean that the editor should always be the first thing to scroll until it bottoms or tops out, or that only the respective pane should scroll when moused over?

**Comment by hwkr** [comment]
Uhh if you're over the editor it should be the only thing that is allowed to scroll. If it can't scroll (not tall enough) nothing should scroll (IMHO).

**Comment by bndnio** [comment]
Agreed 👍
