### ISSUE TITLE
Touch up Team section

### ISSUE THREAD

**Issue by kelseyll** [Wubbadub/ClubHub#103]
__Description:__
Touch up typography styles and padding in Team section. Low priority.

__Requires:__
* styling

__Breakdown:__

- [ ] Add min-width so shorter names don't collapse (like in screenshot below)
- [ ] Touch up typography styles
- [ ] Touch up padding

__Time Estimation:__
1 hrs.

![image](https://cloud.githubusercontent.com/assets/10638534/20643863/ca913590-b3d8-11e6-9b33-1e6498a7cd44.png)

**Comment by okjuan** [comment]
@kelseyll It would be awesome to also prettify the layout, specifically aiming to separate a club member/admin's name and their role in the club. Currently, this is the same field.

**Comment by hwkr** [comment]
To clarify: this is in the Classic template?

**Comment by kelseyll** [comment]
@jcgallegdup yah I agree, I'll add that to the description. @hwkr yes, isn't it the only template we have?

**Comment by hwkr** [comment]
I meant as opposed to the editor.

**Comment by kelseyll** [comment]
ahh. Yes this issue is for the team section in the template specifically. There's another issue to beautify the editor pane: https://github.com/Wubbadub/ClubHub/issues/76
