### ISSUE TITLE
Test User Interaction

### ISSUE THREAD

**Issue by okjuan** [Wubbadub/ClubHub#107]
__Description:__
Test our interface with users and summarize results.

__Requires:__
* Meet with multiple club admins and give them a starting point and a goal. 
* Study them as they use the interface. 
* If possible, have them speak aloud as they work through the use case.

__Breakdown:__
- [x] set up meetings
- [x] prep procedure
- [x] test and gather data
- [x] summarize results

__Time Estimation:__
8 hrs.

**Comment by JoshDPearson** [comment]
https://paper.dropbox.com/doc/Beta-Testing-Results-XlcK9jiIh2kumq8wZnT3Z

**Comment by kelseyll** [comment]
Are we safe to close this? (great work guys)

**Comment by JoshDPearson** [comment]
I think so
