### ISSUE TITLE
Improve Editor UX

### ISSUE THREAD

**Issue by bndnio** [Wubbadub/ClubHub#112]
__Description:__
To improve user experience, we must build a walkthrough and improve the usability of our editor.

__Requires:__
* Editor and EditorSections to be implemented

__Breakdown:__
- [ ] ~Add walkthrough button (for now)~
- [ ] ~Add banners explaining what to do~
- [ ] ~Add step-through process for on boarding~
- [ ] Highlight webpage sections when focused in editor pane

__Time Estimation:__
3/4 hrs.

**Comment by okjuan** [comment]
I really like your 'walkthrough button' idea to help focus the effort on having an onboarding process and avoid getting bogged down by the task of implementing triggers and getting the timing just right.
