### ISSUE TITLE
Create Final Project Documentation

### ISSUE THREAD

**Issue by JoshDPearson** [Wubbadub/ClubHub#134]
__Description:__

Description of main use cases, architectural overview, main APIs/features, installation and usage instructions, the user study, and any other relevant information.

[Example Documentation](https://docs.google.com/viewer?a=v&pid=sites&srcid=ZGVmYXVsdGRvbWFpbnxjbG91ZHdlYjEwYXxneDo2Y2Q3MmZjNzk1ODdmNzA2)

__Requires:__

__Breakdown:__

__Time Estimation:__
3 hrs.

**Comment by kelseyll** [comment]
https://docs.google.com/document/d/1sf-g-_QSuCTjyq68KlOve1rHIBQazbRTM9p8-YN89IQ/edit?usp=sharing
