### ISSUE TITLE
Create server daemon

### ISSUE THREAD

**Issue by okjuan** [Wubbadub/ClubHub#14]
Created as per a comment made by Ben -- not exactly sure what this means.

**Comment by okjuan** [comment]
@hwkr I still don't know what you meant by this.

**Comment by hwkr** [comment]
Something like [this](http://blog.terminal.com/using-daemon-to-daemonize-your-programs/) but Cliff made some good points in his talk so maybe we should do somehting else.

**Comment by hwkr** [comment]
I'm going to close this because it's a pain and takes focus away from features, we can bring it back if we care.
