### ISSUE TITLE
Develop splash page

### ISSUE THREAD

**Issue by kelseyll** [Wubbadub/ClubHub#24]

**Comment by kelseyll** [comment]
![screen shot 2016-10-11 at 11 50 57 pm](https://cloud.githubusercontent.com/assets/10638534/19300264/3a49d552-900e-11e6-8c2e-5b6aa4c14894.png)
![screen shot 2016-10-11 at 11 51 25 pm](https://cloud.githubusercontent.com/assets/10638534/19300266/3a518bbc-900e-11e6-9aea-59b9d8d53ad5.png)
![screen shot 2016-10-11 at 11 51 50 pm](https://cloud.githubusercontent.com/assets/10638534/19300265/3a4e33fe-900e-11e6-9592-d8c9790b3840.png)
![screen shot 2016-10-11 at 11 50 50 pm](https://cloud.githubusercontent.com/assets/10638534/19300267/3a51e77e-900e-11e6-9729-41ebe64f3f52.png)

**Comment by hwkr** [comment]
Can you link to the codepen?

**Comment by kelseyll** [comment]
The code is in the repo, I didn't make a code pen.

**Comment by hwkr** [comment]
Okay!
