### ISSUE TITLE
Design Editor

### ISSUE THREAD

**Issue by kelseyll** [Wubbadub/ClubHub#27]

**Comment by JoshDPearson** [comment]
Ben, Juan and I sat down today for a bit and and worked a little bit on some paper prototyping while discussing the flow for a few use cases. Just wanted to share a few of the ideas that developed from it:

One of the main take aways from the discussion was the idea of focusing the scope of the project a little bit. A couple ways we thought of to do this were:

Focus on implementation for UVIC first. I believe Ben tonight bought the domain name "uvic.club" tonight for < $10. So what this might look like is our club admins would register, create, and edit their websites at "tryclubhub.com", but the url for their clubhub website would be "<clubtoken>.uvic.club", "uvic.<clubtoken>.club" or some variation thereof. The reasoning for this is to save us some of the headache of having to include multiple universities/colleges in our branding.

Postpone or abandon the directory feature. While I think we all agree it is for the most part inline with our mission statement, the directory feature's usefulness or payoff is directly proportionate to the number of UVIC clubs that are using it. Within this semester it is very likely that we will not have enough club websites registered to really showcase the benefit of the directory feature. By postponing (probably beyond Milestone 3) or abandoning the directory feature this allows us to really focus our efforts on our MVP the simple club website creation.

Some of the points of discussion regarding flows that came up were:

The representation of an admin who leads multiple clubs. Two ideas were suggested for this: 
     The first was Ben was working on a mock up earlier that I think most people saw. It had a left justified accordion menu for the admin to edit his cub with. The club(s) belonging to that admin would all be visible in that accordion.  
     The second was a page in between signing in/registering that had a display of a card for each club belonging to the admin.

The flow of a user who wants to pass leadership to another, as well as the situation of a club with more than one admin also came up. I think passing leadership is a milestone 3 feature, and a club with more than one admin might be a bit of a fringe case, but these are probably worth discussing sooner than later. 

Sorry for the word vomit, I should have been taking notes while we were discussing it. Just some things to mull over and then we can discuss them in our next meeting! (Ben and Juan please add anything I missed or clarify anything I mixed up!)

@kelseyll @hwkr @Inschato @BrendonEarl @jcgallegdup

**Comment by hwkr** [comment]
Well put @JoshDPearson, some clarifications for my stuff:
- Hosting the club sites at `uvic.club` was more about nailing the UVic club audience than multi-college branding stuff. I think if we want to make this product awesome in the next 4 months we should focus down UVic and make the best product for UVic clubs. It's like, would you prefer `canoe.uvic.hubsite.club` or `canoe.uvic.club`. If our goal is really club image than I think we should give them the best domains possible.
- For admins with multiple clubs I wasn't actually envisioning them in the accordion but rather in a dropdown switcher in the top right corner. If you check out the Facebook developer panel it's similar.

![Facebook Developer Panel](https://cloud.githubusercontent.com/assets/6374090/19621023/f376d0ca-983d-11e6-8a04-68abcada7f5d.png)

**Comment by kelseyll** [comment]
Thanks for the explanation @JoshDPearson !
- I agree about putting off the directory feature 👍 
- I agree about putting off the edge case of owning multiple clubs for milestone 3, but also having a plan for it in our editor mockups 👍 
- I agree about passing leadership being a milestone 3 feature 👍 
- I do agree about using uvic.club for now, BUT I think we should be prepared to answer the big problems that arise from sticking with university specific domain names if we have any plans of scaling:
  -- We have to own/purchase/manage and update a unique domain for every university that clubhub is used at. All of these things would be costly, time consuming, and make it much more difficult to scale (if a club at U of Waterloo wants to create a clubhub page, they have to wait until we buy a domain for that university)
  -- If we want to change it later so we don't use university specific domain names when we have ~100 clubs at UVic, we then have to change each club's domain name (this is awhile down the line when clubs already have their domain on posters, assets, etc)
  -- @hwkr you point out that we'd have to use`canoe.uvic.hubsite.club` if we used another global domain, but couldn't we just leave out uvic and use `canoe.hubsite.co`? I do agree that it makes the experience of UVic clubs much better though ( `canoe.uvic.club` is really great )

Again, I'm cool with using it for now, but we should be prepared to  at least answer these questions, and at least think of better ways we could scale if we continue using uvic.club

**Comment by bndnio** [comment]
Well said Kelsey! I agree 100% with you all except for one thing. 
I think we should aim to have the club directory page up for milestone 3. I think it drives the other half of our use case, and required relatively little work to implement in comparison and provides a fair bit of value. In addition, clubs will be motivated to get on that list for added exposure by joining our platform.

**Comment by hwkr** [comment]
@kelseyll I totally agree, I think we should keep trying to figure out what the best general domain solution could be as well

**Comment by kelseyll** [comment]
@BrendonEarl @hwkr @JoshDPearson @jcgallegdup @Inschato

--> [Invision Prototype of Editor Mockup](https://invis.io/YC94GKSNQ#/200790067_Hubsite)

**Comment by hwkr** [comment]
Seems like we have this mostly hashed out so I'm going to close this.
