### ISSUE TITLE
Communicate product better - design/develop new landing page

### ISSUE THREAD

**Issue by okjuan** [Wubbadub/ClubHub#29]
**Feature Name** 
Create a Club Page as a Club Admin

**Description**
Goal: express clearly what clubhub _is_ and what problem it will solve.

**Requires**
- Visual design
- Concise wording, based on Problem Definition in wiki

**Due:** 
Milestone 2, Nov 4th

**Time Estimation:** 
2hrs

**Comment by okjuan** [comment]
![splash page sketch](https://cloud.githubusercontent.com/assets/13096220/19622229/d5694f38-9859-11e6-958e-6c9b830d4d74.jpg)

**Comment by kelseyll** [comment]
LANDING COPY https://paper.dropbox.com/doc/Landing-Copy-pxXFznQD3GDxliDN480Vs

**Comment by kelseyll** [comment]
https://github.com/Wubbadub/ClubHub/pull/78
