### ISSUE TITLE
Develop account authentication

### ISSUE THREAD

**Issue by okjuan** [Wubbadub/ClubHub#3]
Implement authentication initially via Google Sign-In APIs.
# Progress
- [x] Set up Google Sign-In
- [x] Integrate authentication into sign-up and database
- [x] Integrate authentication into sign-in

**Comment by okjuan** [comment]
some options:
- OAuth
- Google
- Facebook

**Comment by hwkr** [comment]
Created a Facebook app https://developers.facebook.com/apps/335271516823992/.

**Comment by hwkr** [comment]
Possible design issue to consider is users is club admins with multiple clubs. They need a way to switch.

**Comment by Inschato** [comment]
Closed via #111
