### ISSUE TITLE
Send feature list and who did what document to Mentors

### ISSUE THREAD

**Issue by kelseyll** [Wubbadub/ClubHub#31]

**Comment by kelseyll** [comment]
Sent on Monday October 17th

"Dear ClubHub team,

Please send us a document explaining how did you split the work for Milestone 1? It should be a list of the features that were done, who worked on them, and approx. how much time was spent implementing each of these features.

Regards,
Alexey"

**Comment by okjuan** [comment]
#### Off the top of my head

**Kelsey**
- hubsite template
- splash page
- Club Promo Email

**Brendon**
- server setup
- request handling
- _Github issue_ task management

**Juan** 
- server setup
- request handling
- Typeform

**Josh** 
- Club Signup Form 
- Typeform
- Club Promo Email

**Ben**
- milestone 1 prep (slides)
- project management

Andrew: 
- feature list
- problem definition

**Comment by kelseyll** [comment]
This is great, thanks Juan!!!

**Comment by kelseyll** [comment]
https://paper.dropbox.com/doc/Milestone-1-effort-Xf81fkhlfCOBugIY1cnrL
