### ISSUE TITLE
Investigate options for testing frameworks

### ISSUE THREAD

**Issue by okjuan** [Wubbadub/ClubHub#32]
**Feature Name**
Testing

**Description**
Find a testing framework to use throughout development.

**Requires**
- [requirement 1]

**Subtask Breakdown**
- [ ] Outline requirements for testing framework
- [ ] Find a list of candidates that adhere to requirements

**Due**
Milestone []

**Time Estimation:**
[]hrs.

**Comment by hwkr** [comment]
Closing this as duplicate of #33.
