### ISSUE TITLE
Set up Continuous Integration

### ISSUE THREAD

**Issue by hwkr** [Wubbadub/ClubHub#36]
Set up Travis CI for the project to validate webpack.

**Requires**
- Webpack working
- Travis CI Account

**Subtask Breakdown**
- [x] Set up Travis account
- [x] Configure build script
- [x] Enable CI

**Due**
Milestone 2

**Time Estimation:**
4hrs.

**Comment by hwkr** [comment]
Ready to go at 8e91453. [Travis CI won't allow syncing](https://twitter.com/traviscistatus/status/789558247745200128) with GitHub due to the recent DDoS attacks so this is temporarily on hold.

**Comment by hwkr** [comment]
[Travis CI is back up!](https://twitter.com/traviscistatus/status/789758256801427456) Testing the build.

**Comment by hwkr** [comment]
CI is enabled!
![image](https://cloud.githubusercontent.com/assets/6374090/19621126/fb61c568-983f-11e6-9564-1ae1fd44f2ec.png)

**Comment by hwkr** [comment]
CI is tested and awaiting review/merge in PR #38.

**Comment by okjuan** [comment]
Reviewed, approved, and merged into **develop** branch.
