### ISSUE TITLE
Set up Google Analytics

### ISSUE THREAD

**Issue by okjuan** [Wubbadub/ClubHub#4]
Connect Google Analytics to the landing page to get conversion information.
# Progress
- [x] Set up Google Analytics account
- [x] Integrate analytics codes into landing page.

**Comment by okjuan** [comment]
highly recommended by speakers so far: segment.io

**Comment by hwkr** [comment]
@JoshDPearson do you want to take a shot at this?

**Comment by JoshDPearson** [comment]
@hwkr  Yeah, I'll give it a shot! We'd like this done for milestone 2?
