### ISSUE TITLE
Design club verification system

### ISSUE THREAD

**Issue by okjuan** [Wubbadub/ClubHub#5]

**Comment by okjuan** [comment]
some options:
- UVSS
- ClubHub sponsored verification (like Twitter 'verified')
- Web of trust

**Comment by bndnio** [comment]
New option introduced:
- Campus Rep

**Comment by JoshDPearson** [comment]
We just spoke about this so I thought I'd jot it down here before we forget. Brendon mentioned having a feature where club pages can be created but will not go live until someone UVSS, ClubHub verification, or Campus Rep approves it.

**Comment by kelseyll** [comment]
Added to final documentation!
