### ISSUE TITLE
Add a max width & length for club description on Hubsite

### ISSUE THREAD

**Issue by okjuan** [Wubbadub/ClubHub#66]
__Description:__
At the moment, it grows in width and allows for indefinite length.

__Requires:__
* styling

__Breakdown:__
- [x] fix width
- [x] fix length

__Time Estimation:__
1 hrs.

**Comment by hwkr** [comment]
It would probably be better to just cap the size of the input in db/editor.

**Comment by kelseyll** [comment]
https://github.com/Wubbadub/ClubHub/tree/fix/66/hubsite-description-width

**Comment by okjuan** [comment]
#102 merged
