### ISSUE TITLE
Add logic for maintaining a variable number of Club Reps

### ISSUE THREAD

**Issue by okjuan** [Wubbadub/ClubHub#68]
__Description:__
Feature allowing club admin to maintain the (amount of) club reps under 'Team' Editor Section.

__Requires:__
* changing `team` object to contain a list of team members instead of separate objects for every team member. 
* visibility in GUI (under 'Team' Editor Section)
* logic to add a new person to data object, under site>sections>team 
  - causes new input fields to appear in 'Team' Editor Section 
  - causes the new club rep to appear in Team component
* logic to remove a person from data object, under site>sections>team 
  - deletes input fields for specific person
  - deletes the club rep from Team component
* New logic for manipulating site data object
* GUI for easy use

__Breakdown:__
- [ ] Add logic for adding a club rep
- [ ] Set a maximum?
- [ ] Add GUI prompt for adding a club rep
- [ ] Add logic for removing a club rep
- [ ] Add GUI prompt for removing a club rep

__Time Estimation:__
4-5 hrs.

**Comment by hwkr** [comment]
I'm not sure if this should be in the Editor

**Comment by kelseyll** [comment]
https://github.com/Wubbadub/ClubHub/issues/56
