### ISSUE TITLE
Link Editor to Splash

### ISSUE THREAD

**Issue by okjuan** [Wubbadub/ClubHub#71]
__Description:__
Link component in SignUp component needs points to '/editor' but our editor currently only exists on '/editor/something'

__Requires:__
* █

__Breakdown:__
- [ ] 1st
- [ ] 2nd
- [ ] 3rd

__Time Estimation:__
█ hrs.

**Comment by kelseyll** [comment]
I changed the path in `SignUp.jsx` from `/editor` to `/editor/create` in #78 so that it would work.

should I revert it back? or keep it.

**Comment by hwkr** [comment]
That's fine, we'll sort it out

**Comment by hwkr** [comment]
This kinda works, I'ma close it.
