### ISSUE TITLE
Interface Site/Routing with API calls

### ISSUE THREAD

**Issue by bndnio** [Wubbadub/ClubHub#73]
__Description:__
Need to call AJAX requests to GET data to populate sites and POST request to modify data in the db

__Requires:__
* DB to be set up
* API to be created
* Routing to be done

__Breakdown:__
- [x] Implement GET request (for site)
- [x] Implement POST request (for editor)

__Time Estimation:__
2 hrs.

**Comment by hwkr** [comment]
Closed in #80.
