### ISSUE TITLE
Fix team editor section issues

### ISSUE THREAD

**Issue by hwkr** [Wubbadub/ClubHub#86]
__Description:__
Creates a weird circular dependency right now. Error when you try to save,

```
Uncaught TypeError: Converting circular structure to JSON(…)
```

__Breakdown:__
- [ ] Fix the saving
- [ ] Also fix the keying

__Time Estimation:__
2 hrs.

**Comment by okjuan** [comment]
Accidentally wrote a new version of this. Closed as duplicate.
