### ISSUE TITLE
Add functionality to delete unwanted elements in the editor

### ISSUE THREAD

**Issue by kelseyll** [Wubbadub/ClubHub#88]
__Description:__
Design and develop an easy way to delete elements from the template that a user wouldn't want. An example use case being a club who doesn't have an twitter account and would like to remove the social link and icon.

__Breakdown:__
- [ ] Decide what elements can be removed
- [ ] Design solution
- [ ] Develop solution

__Time Estimation:__
3 hrs.

**Comment by kelseyll** [comment]
Design and develop an easy way to delete elements from the template that a user wouldn't want.

**Use Case:**  a club doesn't have an twitter account and would like to remove the social link and icon

**Time Esitmate:** 3hrs

**Comment by okjuan** [comment]
closing as duplicate of #68 #56
