### ISSUE TITLE
Fix Logic in Team Editor Section for Updating the Data Object

### ISSUE THREAD

**Issue by okjuan** [Wubbadub/ClubHub#95]
__Description:__
Faulty logic in Team Editor Section causes a "Converting circular structure to JSON" error.

__Requires:__
* debug & refactor

__Breakdown:__
- [x] try editing a team member's info and observe error
- [x] fix logic

__Time Estimation:__
1 hrs.

**Comment by bndnio** [comment]
@jcgallegdup check out issue #86 -- looks like either a duplicate or same issue with added requirements?

**Comment by hwkr** [comment]
Lol yep

**Comment by okjuan** [comment]
Oops!
