### ISSUE TITLE
Add Feedback Upon Saving Changes to Site

### ISSUE THREAD

**Issue by okjuan** [Wubbadub/ClubHub#98]
__Description:__
When a club admin makes changes to their site content and hits 'Save' on the editor, they should get some feedback that their site was updated.

__Requires:__
* Design choice regarding the feedback medium 
* Implementation

__Breakdown:__
- [x] Experiment with different ideas
- [x] Choose medium (e.g. a fading banner?)
- [x] Implement to show upon hitting 'Save'

__Time Estimation:__
1 hrs.

**Comment by hwkr** [comment]
I was going to put a checkmark in the `Save` button on success.

**Comment by kelseyll** [comment]
This seems done:
![image](https://cloud.githubusercontent.com/assets/10638534/20861914/b5366b1a-b951-11e6-86ee-8c3e1fb44f1c.png)
